[workspace]
members = [
  "crates/bullet-core",
  "crates/bullet-engine",
  "crates/bullet-data",
  "crates/bullet-backtest",
  "crates/bullet-cli",
  "crates/bullet",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/No-Trade-No-Life/Bullet"
